# Generated by Django 2.2.12 on 2020-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200605_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='img_profile/'),
        ),
    ]
